name: Build VenomOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y nasm make qemu-system-x86

      - name: Build
        run: make